application:
  name: latency-troubleshooter-app
  results:
    generation:
      size: 100000

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, beans, env
  endpoint:
    health:
      show-details: always

spring:
  main:
    lazy-initialization: true

